Break out all getData methods in contractWrappers
kleros/kleros-api pull request #89
Opened 2018-02-28 16:21 UTC by zetsin

Break all attributes as what @n1c01a5 suggested

2018-02-28 16:28 UTC, n1c01a5 commented
yes for https://github.com/kleros/kleros-api/issues/41

2018-02-28 21:28 UTC, epiqueras requested changes
Hi @zetsin,

Thanks for the PR, it looks good, just needs a few tweaks.

2018-02-28 21:28 UTC, epiqueras commented on src/contractWrappers/ArbitrableTransactionWrapper.js
> +    arbitrableTransaction.abi.filter(abi => abi.type === 'function').forEach(abi => {
We need to check if the function is `constant` too.

2018-02-28 21:28 UTC, epiqueras commented on src/contractWrappers/ArbitrableTransactionWrapper.js
> +        if(abi.name === 'partyAFee' || abi.name === 'partyBFee') {
Instead of doing this. We can have an object that maps `type`s or `name`s to a `parse` function.

E.g.

```js
const parsers = {
  // Types
  int256: v => v.toNumber(),
  // Names
  partyAFee: v => web3.fromWei(v, 'ether')
}
```

Then parse like this:

```js
return parsers[abi.name](parsers[abi.type](result))
```

2018-02-28 21:28 UTC, epiqueras commented on src/contractWrappers/PinakionWrapper.js
> +
We can move these functions into a separate file in the `utils` folder.

And then call it like this in the constructors:

```js
setABIGetters(this, abi)
```

2018-03-01 16:39 UTC, zetsin commented
ok, should I handle the case of multiple outputs? Is it an object or array?

2018-03-02 19:37 UTC, epiqueras requested changes
Looks great!

I replied to your question.

2018-03-02 19:37 UTC, epiqueras commented on src/utils/index.js
> +        // FIXME: do we need to handle multiple outputs?
Yes, we can do something like this:

```js
// Outside setABIGetters
const parse = (type, name, value) => {
  let result = value
  if (parsers.types[type]) result = parsers.types[type](result)
  if (parsers.names[name]) result = parsers.types[name](result)
  return result
}

// Inside setABIGetters
return abi.outputs.length === 1 ? parse(abi.outputs[0].type, abi.name, result)
  : abi.outputs.map(({ type }, i) => parse(type, abi.name, result[i]))
```

2018-03-03 15:53 UTC, zetsin commented
It's fine now, another question:
I can't pass `yarn test` even on the *master* branch, how could I set up the environment for testing?

2018-03-03 19:26 UTC, n1c01a5 commented
@zetsin for the tests you need to run `ganache`
```
yarn run ganache-cli
yarn test
```
but for now the tests failed.

2018-03-03 20:43 UTC, epiqueras commented
@n1c01a5 
@zetsin 
The tests are not failing because he wasn't running ganache.
See the error logs:

![screen shot 2018-03-03 at 12 41 02 pm](https://user-images.githubusercontent.com/19157096/36939088-60ed8264-1ee0-11e8-8eb3-774153c7e6c4.png)

And yes, the tests are failing on `master` but they are passing on `develop`.

2018-03-03 20:48 UTC, n1c01a5 commented
@epiqueras I think the tests are not updated with the new attribute `title` on the deploy function for contract arbitrable, see https://github.com/kleros/kleros-api/blob/6bfb6e954dc93c75b2e16e1a3bb4f13633d86170/src/abstractWrappers/ArbitrableContract.js#L41

2018-03-03 20:50 UTC, epiqueras commented
@n1c01a5 
It's still failing with the same error messages after you merged develop in.

So the error has something to do with the changes on this repo.

2018-03-07 14:48 UTC, zetsin commented
I realize that you refactored the project currently, should I close this pull request? @epiqueras

2018-03-08 00:50 UTC, epiqueras commented
@zetsin 
If you can rebase it onto `develop` and fix it so it passes the tests, that would be awesome. Otherwise, one of us can take care of it when we have time.

2018-03-08 06:34 UTC, zetsin commented
Hi @epiqueras .
I always cannot pass `yarn test` on `develop` branch due to so many timeout.
After I prolong the timeout value in the testing file, there is a failure happened now:
```cmd
  ● Kleros › KlerosPOC dispute resolution flow

    expect(received).toEqual(expected)
    
    Expected value to equal:
      1
    Received:
      0

      652 |         true
      653 |       )
    > 654 |       expect(jurorStatefullNotifications.length).toEqual(1)
      655 |       expect(jurorStatefullNotifications[0].notificationType).toEqual(
      656 |         notificationConstants.TYPE.CAN_VOTE
      657 |       )
```

2018-03-08 16:03 UTC, epiqueras commented
@zetsin 
Yeah, the notifications part of the test is not deterministic. @satello is working on that.

For now, you can comment out that assertion.

2019-01-02 18:11 UTC, closed without merging